#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : kitemmodels
Version  : 5.53.0
Release  : 11
URL      : https://download.kde.org/stable/frameworks/5.53/kitemmodels-5.53.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.53/kitemmodels-5.53.0.tar.xz
Source99 : https://download.kde.org/stable/frameworks/5.53/kitemmodels-5.53.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: kitemmodels-data = %{version}-%{release}
Requires: kitemmodels-lib = %{version}-%{release}
Requires: kitemmodels-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : qtbase-dev mesa-dev

%description
# KItemModels
Set of item models extending the Qt model-view framework
## Introduction

%package data
Summary: data components for the kitemmodels package.
Group: Data

%description data
data components for the kitemmodels package.


%package dev
Summary: dev components for the kitemmodels package.
Group: Development
Requires: kitemmodels-lib = %{version}-%{release}
Requires: kitemmodels-data = %{version}-%{release}
Provides: kitemmodels-devel = %{version}-%{release}

%description dev
dev components for the kitemmodels package.


%package lib
Summary: lib components for the kitemmodels package.
Group: Libraries
Requires: kitemmodels-data = %{version}-%{release}
Requires: kitemmodels-license = %{version}-%{release}

%description lib
lib components for the kitemmodels package.


%package license
Summary: license components for the kitemmodels package.
Group: Default

%description license
license components for the kitemmodels package.


%prep
%setup -q -n kitemmodels-5.53.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1544488447
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1544488447
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kitemmodels
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/kitemmodels/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/xdg/kitemmodels.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KItemModels/KBreadcrumbSelectionModel
/usr/include/KF5/KItemModels/KCheckableProxyModel
/usr/include/KF5/KItemModels/KConcatenateRowsProxyModel
/usr/include/KF5/KItemModels/KDescendantsProxyModel
/usr/include/KF5/KItemModels/KExtraColumnsProxyModel
/usr/include/KF5/KItemModels/KLinkItemSelectionModel
/usr/include/KF5/KItemModels/KModelIndexProxyMapper
/usr/include/KF5/KItemModels/KRearrangeColumnsProxyModel
/usr/include/KF5/KItemModels/KRecursiveFilterProxyModel
/usr/include/KF5/KItemModels/KSelectionProxyModel
/usr/include/KF5/KItemModels/kbreadcrumbselectionmodel.h
/usr/include/KF5/KItemModels/kcheckableproxymodel.h
/usr/include/KF5/KItemModels/kconcatenaterowsproxymodel.h
/usr/include/KF5/KItemModels/kdescendantsproxymodel.h
/usr/include/KF5/KItemModels/kextracolumnsproxymodel.h
/usr/include/KF5/KItemModels/kitemmodels_export.h
/usr/include/KF5/KItemModels/klinkitemselectionmodel.h
/usr/include/KF5/KItemModels/kmodelindexproxymapper.h
/usr/include/KF5/KItemModels/krearrangecolumnsproxymodel.h
/usr/include/KF5/KItemModels/krecursivefilterproxymodel.h
/usr/include/KF5/KItemModels/kselectionproxymodel.h
/usr/include/KF5/kitemmodels_version.h
/usr/lib64/cmake/KF5ItemModels/KF5ItemModelsConfig.cmake
/usr/lib64/cmake/KF5ItemModels/KF5ItemModelsConfigVersion.cmake
/usr/lib64/cmake/KF5ItemModels/KF5ItemModelsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5ItemModels/KF5ItemModelsTargets.cmake
/usr/lib64/libKF5ItemModels.so
/usr/lib64/qt5/mkspecs/modules/qt_KItemModels.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5ItemModels.so.5
/usr/lib64/libKF5ItemModels.so.5.53.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kitemmodels/COPYING.LIB
