#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : kitemmodels
Version  : 5.48.0
Release  : 1
URL      : https://download.kde.org/stable/frameworks/5.48/kitemmodels-5.48.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.48/kitemmodels-5.48.0.tar.xz
Source99 : https://download.kde.org/stable/frameworks/5.48/kitemmodels-5.48.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: kitemmodels-lib
Requires: kitemmodels-license
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde

%description
# KItemModels
Set of item models extending the Qt model-view framework
## Introduction

%package dev
Summary: dev components for the kitemmodels package.
Group: Development
Requires: kitemmodels-lib
Provides: kitemmodels-devel

%description dev
dev components for the kitemmodels package.


%package lib
Summary: lib components for the kitemmodels package.
Group: Libraries
Requires: kitemmodels-license

%description lib
lib components for the kitemmodels package.


%package license
Summary: license components for the kitemmodels package.
Group: Default

%description license
license components for the kitemmodels package.


%prep
%setup -q -n kitemmodels-5.48.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532359697
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1532359697
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kitemmodels
cp COPYING.LIB %{buildroot}/usr/share/doc/kitemmodels/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KItemModels/KBreadcrumbSelectionModel
/usr/include/KF5/KItemModels/KCheckableProxyModel
/usr/include/KF5/KItemModels/KConcatenateRowsProxyModel
/usr/include/KF5/KItemModels/KDescendantsProxyModel
/usr/include/KF5/KItemModels/KExtraColumnsProxyModel
/usr/include/KF5/KItemModels/KLinkItemSelectionModel
/usr/include/KF5/KItemModels/KModelIndexProxyMapper
/usr/include/KF5/KItemModels/KRearrangeColumnsProxyModel
/usr/include/KF5/KItemModels/KRecursiveFilterProxyModel
/usr/include/KF5/KItemModels/KSelectionProxyModel
/usr/include/KF5/KItemModels/kbreadcrumbselectionmodel.h
/usr/include/KF5/KItemModels/kcheckableproxymodel.h
/usr/include/KF5/KItemModels/kconcatenaterowsproxymodel.h
/usr/include/KF5/KItemModels/kdescendantsproxymodel.h
/usr/include/KF5/KItemModels/kextracolumnsproxymodel.h
/usr/include/KF5/KItemModels/kitemmodels_export.h
/usr/include/KF5/KItemModels/klinkitemselectionmodel.h
/usr/include/KF5/KItemModels/kmodelindexproxymapper.h
/usr/include/KF5/KItemModels/krearrangecolumnsproxymodel.h
/usr/include/KF5/KItemModels/krecursivefilterproxymodel.h
/usr/include/KF5/KItemModels/kselectionproxymodel.h
/usr/include/KF5/kitemmodels_version.h
/usr/lib64/cmake/KF5ItemModels/KF5ItemModelsConfig.cmake
/usr/lib64/cmake/KF5ItemModels/KF5ItemModelsConfigVersion.cmake
/usr/lib64/cmake/KF5ItemModels/KF5ItemModelsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5ItemModels/KF5ItemModelsTargets.cmake
/usr/lib64/libKF5ItemModels.so
/usr/lib64/qt5/mkspecs/modules/qt_KItemModels.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5ItemModels.so.5
/usr/lib64/libKF5ItemModels.so.5.48.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/kitemmodels/COPYING.LIB
